### ISSUE TITLE
grunt-wiredep does not find techne.min.css file because of bower.json

### ISSUE THREAD

**Issue by ruhkopf** [hybris/techne#120]
Hi there,

We're using [grunt-wiredep](http://grunt-tasks.com/grunt-wiredep/) to automatically include css and js files from our Bower dependencies. This works fine for Techne's JavaScript file techne.min.js. However, it does not work for the CSS file techne.min.css. 

This can be fixed by specifying the file in bower.json instead of the directory:
```
  "main":[
    "dist/js/techne.min.js",
    "dist/css/techne.min.css"
  ],
```
Could you please fix this?

Thanks
Patrick

**Comment by jeremytrawls** [comment]
Hi @ruhkopf,

I can help you out with that.  First could you share which release of techné you're using?

**Comment by ruhkopf** [comment]
Hi Jeremy,

I installed it via Bower. I got 0.2.2.

**Comment by jeremytrawls** [comment]
@ruhkopf  we just released 0.2.3 which should fix the issues that you were seeing.

Please update your bower.json to use 0.2.3 and then run an bower update.  

Thanks.

**Comment by ruhkopf** [comment]
@jeremytrawls Thanks for the prompt reply. However, I'm afraid it doesn't seem to be fixed in 0.2.3, see https://github.com/hybris/techne/blob/v0.2.3/bower.json.

It's still specifying 
```
 "main":[
    "dist/js/techne.min.js",
    "dist/css/"
  ],
```
But it should specify:
```
 "main":[
    "dist/js/techne.min.js",
    "dist/css/techne.min.css"
  ],
```

**Comment by jeremytrawls** [comment]
@ruhkopf sorry about that sir.  Do an update of 0.2.3 and it should be corrected.

**Comment by ruhkopf** [comment]
Yep, now it's working. :) Thx!
