### ISSUE TITLE
License

### ISSUE THREAD

**Issue by reiz** [hybris/techne#47]
Under which license is this repo published? In the [bower.json is MIT defined](https://github.com/hybris/techne/blob/master/bower.json#L27).  But the [LICENSE](https://github.com/hybris/techne/blob/master/LICENSE#L1) file in the root repo says Apache-2.0 License. What is it?

**Comment by jeremytrawls** [comment]
@reiz sorry for getting back to you late.  our bower.json has been updated with the correct license.  We are using Apache 2.0

**Comment by reiz** [comment]
Awesome :+1:
